### ISSUE TITLE
Attribute names in EO collide with Python keywords

### ISSUE THREAD

**Issue by nikololiahim** [nikololiahim/eo-python#19]
All atomic attributes in EO are lower case, however in the current version of API they are title case. 

**Making all attributes of API lowercase** isn't currently possible because some of their names collide with Python keywords, such as `or`, `and`, `if`, etc. 

**Doing name transformations during translation** is also not a desirable approach, because we don't know for sure which attributes we need to translate. EO XMIR provides no way of telling apart atomic (`.and`, `.if`, etc.) and non-atomic (`distance`, `radius`, etc.) attributes. 

Something needs to be done about this.

**Comment by eyihluyc** [comment]
Proposed solution:
* Internal representation of all attributes gets `attr_` as prefix. For example, an attribute named `distance` in EO, would be named `attr_distance` in our generated python code.
* Special attributes `__PHI__`, `__PARENT__`, `__SELF__` were renamed to `attr__phi`, `attr__parent`, `attr__self`. It excludes the possibility of collision between user-defined names such as `phi` with python's internal attributes that we introduced, because identifiers in EOlang cannot start with `_`
